[[protocols]]
name = "myremote"
protocol = "nec"
[protocols.scancodes]
0x19 = "KEY_NUMERIC_0"
0x45 = "KEY_NUMERIC_1"
0x46 = "KEY_NUMERIC_2"
0x47 = "KEY_NUMERIC_3"
0x44 = "KEY_NUMERIC_4"
0x40 = "KEY_NUMERIC_5"
0x43 = "KEY_NUMERIC_6"
0x07 = "KEY_NUMERIC_7"
0x15 = "KEY_NUMERIC_8"
0x09 = "KEY_NUMERIC_9"
0x0d = "KEY_VOLUMEUP"
0x16 = "KEY_VOLUMEDOWN"
0x18 = "KEY_UP"
0x52 = "KEY_DOWN"
0x08 = "KEY_LEFT"
0x5a = "KEY_RIGHT"
0x1c = "KEY_OK"
