[[protocols]]
name = "myremote"
protocol = "sharp"
[protocols.scancodes]
0x10a = "KEY_NUMERIC_0"
0x101 = "KEY_NUMERIC_1"
0x102 = "KEY_NUMERIC_2"
0x103 = "KEY_NUMERIC_3"
0x104 = "KEY_NUMERIC_4"
0x105 = "KEY_NUMERIC_5"
0x106 = "KEY_NUMERIC_6"
0x107 = "KEY_NUMERIC_7"
0x108 = "KEY_NUMERIC_8"
0x109 = "KEY_NUMERIC_9"
0x114 = "KEY_VOLUMEUP"
0x115 = "KEY_VOLUMEDOWN"
0x157 = "KEY_UP"
0x158 = "KEY_DOWN"
0x1f5 = "KEY_LEFT"
0x1f6 = "KEY_RIGHT"
0x116 = "KEY_OK"
